---
# Playbook to power up or down VMware VMs

- name: VMware Power
  hosts: all
  gather_facts: no

  tasks:

  - name: Look up the VM 
#  register: search_result
  vmware.vmware_rest.vcenter_vm_info:
    filter_names:
    - "{{ survey_vm_name}}"
